=== ASSERT-KTH/cvs-vintage/src/dtd/database.dtd
<!-- 
    Torque XML database schema DTD 
    $Id: database.dtd,v 1.3 2001/05/10 23:05:35 jon Exp $
-->

<!ELEMENT app-data (database+)>

<!ELEMENT database (table+)>
<!ATTLIST database
  name CDATA #IMPLIED
  package CDATA #IMPLIED
  baseClass CDATA #IMPLIED
  basePeer CDATA #IMPLIED
>

<!ELEMENT table (column+,foreign-key*,index*,unique*,id-method-parameter*)>
<!ATTLIST table 
  name CDATA #REQUIRED
  javaName CDATA #IMPLIED
  idMethod (idbroker|autoincrement|sequence|none) "none"
  skipSql (true|false) "false"
  abstract (true|false) "false"
  baseClass CDATA #IMPLIED
  basePeer CDATA #IMPLIED
>

<!ELEMENT id-method-parameter EMPTY>
<!ATTLIST id-method-parameter
  name CDATA "default" 
  value CDATA #REQUIRED
>
  
<!ELEMENT column (inheritance*)>
<!ATTLIST column 
  name CDATA #REQUIRED
  javaName CDATA #IMPLIED
  primaryKey (true|false) "false"
  required (true|false) "false"
  type
    (
          BIT  | TINYINT | SMALLINT    | INTEGER    | BIGINT    | FLOAT 
        | REAL | NUMERIC | DECIMAL     | CHAR       | VARCHAR   | LONGVARCHAR 
        | DATE | TIME    | TIMESTAMP   | BINARY     | VARBINARY | LONGVARBINARY 
        | NULL | OTHER   | JAVA_OBJECT | DISTINCT   | STRUCT    | ARRAY 
        | BLOB | CLOB    | REF         | BOOLEANINT | BOOLEANCHAR 
    ) "VARCHAR"       
  size CDATA #IMPLIED
  default CDATA #IMPLIED
  autoIncrement (true|false) "false"
  inheritance (single|false) "false" 
>

<!ELEMENT inheritance EMPTY>
<!ATTLIST inheritance
  key CDATA #REQUIRED 
  class CDATA #REQUIRED
  extends CDATA #IMPLIED
>
                  
<!ELEMENT foreign-key (reference+)>
<!ATTLIST foreign-key 
  foreignTable CDATA #REQUIRED
>
  
<!ELEMENT reference EMPTY>
<!ATTLIST reference 
  local CDATA #REQUIRED
  foreign CDATA #REQUIRED
>

<!ELEMENT index (index-column+)>
<!ATTLIST index 
  name CDATA #REQUIRED
>

<!ELEMENT index-column EMPTY>
<!ATTLIST index-column
  name CDATA #REQUIRED
  size CDATA #IMPLIED
>

<!ELEMENT unique (unique-column+)>
<!ATTLIST unique
  name CDATA #IMPLIED
>

<!ELEMENT unique-column EMPTY>
<!ATTLIST unique-column
  name CDATA #REQUIRED
>

=== ASSERT-KTH/cvs-vintage/src/sql/id-table-schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!-- <!DOCTYPE database SYSTEM 
"http://jakarta.apache.org/turbine/dtd/database.dtd"> -->

<!-- ==================================================================== -->
<!--                                                                      -->
<!-- I D  B R O K E R  S C H E M A                                        -->
<!--                                                                      -->
<!-- ==================================================================== -->
<!-- This is the XML schema use by Torque to generate the SQL for         -->
<!-- ID_TABLE table used by the id broker mechanism in Turbine.           -->
<!-- ==================================================================== -->
<!-- @author: <a href="mailto:jvanzyl@periapt.com">Jason van Zyl</a>      -->
<!-- @version $Id: id-table-schema.xml,v 1.1 2001/12/30 16:07:38 jmcnally Exp $ -->
<!-- ==================================================================== -->

<database name="@DATABASE_NAME@">
  <table name="ID_TABLE" idMethod="idBroker">
    <column name="ID_TABLE_ID" required="true" primaryKey="true" type="INTEGER"/>
    <column name="TABLE_NAME" required="true" size="255" type="VARCHAR"/>
    <column name="NEXT_ID" type="INTEGER"/>
    <column name="QUANTITY" type="INTEGER"/>
    
    <unique>
      <unique-column name="TABLE_NAME"/>
    </unique>        
    
  </table>
</database>
