=== ASSERT-KTH/cvs-vintage/src/dtd/scarab.dtd
<!ELEMENT scarab (user*, module+)>

<!ELEMENT user (firstname, lastname, email)>

<!ELEMENT module (name, code, issue+)>
<!ATTLIST module id CDATA #REQUIRED>
<!ATTLIST module parent CDATA #REQUIRED>

<!ELEMENT issue (artifact-type, committed-by, issue-attribute+, dependency*, attachment*, transaction?)>
<!ATTLIST issue id CDATA #REQUIRED>

<!ELEMENT issue-attribute (name, value, type)>

<!ELEMENT dependency (type, (child | parent))>

<!ELEMENT attachment (name, type, path?, data, mimetype, created-date, modified-date, created-by, modified-by)>

<!ELEMENT modified-date (#PCDATA)>
<!ATTLIST modified-date format CDATA #REQUIRED>

<!ELEMENT created-date (#PCDATA)>
<!ATTLIST created-date format CDATA #REQUIRED>

<!ELEMENT transaction (type, committed-by, activity+)>
<!ATTLIST transaction id CDATA #REQUIRED>

<!ELEMENT activity (activity-attribute, description)>

<!ELEMENT activity-attribute (name, value, old-value, type)>

<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT artifact-type (#PCDATA)>
<!ELEMENT committed-by (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT old-value (#PCDATA)>
<!ELEMENT child (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT modified-by (#PCDATA)>
<!ELEMENT created-by (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== ASSERT-KTH/cvs-vintage/src/dtd/scarab-sample.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE scarab SYSTEM "scarab.dtd">

<!--
Here is what I was thinking the direction of the XML data format should
look like. Of course it is far from 100% complete, but it does show a
few certain things that I would like to achieve. Namely:

#1. Database independence
#2. I put things within tags instead of as XML attributes because they
could contain CDATA. This will allow those tags to contain that type of
information.
#3. The idea is that someone should be able to also (optionally) create
a new scarab database with only user and module information
pre-populated and be able to import an XML file and have it fill in the
rest of the information as necessary. If you think about this further,
one could define things like artifact types and doing a create, 
just by listing the information here instead of having to use the web
interface. That makes things really powerful!
#4. The XML format should be able to be parsed by a human. In the
future, we may support XML submissions via email. This would make it
easier to work with.
#5. In the case of activity-sets, the id number shows the ordering of the 
activity-set within the issue, not necessarily the id number of the primary
key column. This can also be said of the module id, but is less important. 
That is there more for future potential benefit. The issue id is the 
ID_CODE, not the primary key column.
-->

<scarab>
    <module id="6" parent="3">
        <name>Source</name>
        <owner-id>jon@latchkey.com</owner-id>
        <url>/Turbine/Source</url>
        <domain>/Turbine/Source</domain>
        <description>Source</description>
        <code>TBNS</code>

        <user>
          <firstname>Jon</firstname>
          <lastname>Stevens</lastname>
          <email>jon@latchkey.com</email>
          <username>jon@latchkey.com</username>
          <role>Observer</role>
          <role>Partner</role>
          <role>Developer</role>
        </user>

        <issue id="101">
            <artifact-type>Defect</artifact-type>

            <activity-set id="5">
                <type>Create Issue</type>
                <committed-by>jon@latchkey.com</committed-by>
                <activity>
                    <attribute>
                        <name>Status</name>
                        <value>New</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Status set to New
                    </description>
                </activity>
                <activity>
                    <attribute>
                        <name>Priority</name>
                        <value>High</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Priority set to High
                    </description>
                </activity>
            </activity-set>

            <activity-set id="7">
                <type>Edit Issue</type>
                <committed-by>jon@latchkey.com</committed-by>
                <activity>
                    <attribute>
                        <name>Priority</name>
                        <value>Low</value>
                        <old-value>High</old-value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Priority set to Low
                    </description>
                </activity>
                <activity>
                    <attribute>
                        <name>Status</name>
                        <value>unconfirmed</value>
                        <old-value>New</old-value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Status set to unconfirmed
                    </description>
                </activity>
            </activity-set>
            
            <dependency>
                <type>non-blocking</type>
                <child>TBNS203</child>
            </dependency>
                    
            <dependency>
                <type>blocking</type>
                <child>TBNS304</child>
            </dependency>

            <attachment>
                <name>My cool file</name>
                <type>ATTACHMENT</type>
		    
                <!-- 
                Use the path relative to the scarab.attachments.repository
                property in Scarab.properties.
                -->
                <path>relative/path/to/file.txt</path>
                <data></data>
                <mimetype>text/plain</mimetype>
                <created-date format="yyyy-MM-dd">2001-01-01</created-date>
                <modified-date format="yyyy-MM-dd">2001-01-01</modified-date>
                <created-by>jon@latchkey.com</created-by>
                <modified-by>jon@latchkey.com</modified-by>
            </attachment>
        </issue>
        <issue id="203">
            <artifact-type>Defect</artifact-type>

            <activity-set id="5">
                <type>Create Issue</type>
                <committed-by>jon@latchkey.com</committed-by>
                <activity>
                    <attribute>
                        <name>Status</name>
                        <value>Closed</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Status set to Closed
                    </description>
                </activity>
                <activity>
                    <attribute>
                        <name>Resolution</name>
                        <value>Fixed</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Resolution set to Fixed
                    </description>
                </activity>
            </activity-set>
            
            <dependency>
                <type>non-blocking</type>
                <parent>TBNS101</parent>
            </dependency>
        </issue>
        <issue id="304">
            <artifact-type>Defect</artifact-type>
            <activity-set id="100">
                <type>Create Issue</type>
                <committed-by>jon@latchkey.com</committed-by>
                <activity>
                    <attribute>
                        <name>Status</name>
                        <value>Closed</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Status set to Closed
                    </description>
                </activity>
                <activity>
                    <attribute>
                        <name>Resolution</name>
                        <value>Fixed</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Resolution set to Fixed
                    </description>
                </activity>
            </activity-set>
            
            <dependency>
                <type>blocking</type>
                <parent>TBNS101</parent>
            </dependency>
                    
            <dependency>
                <type>blocking</type>
                <parent>TBNS405</parent>
            </dependency>
        </issue>
        <issue id="405">
            <artifact-type>Defect</artifact-type>
            <activity-set id="101">
                <type>Create Issue</type>
                <committed-by>jon@latchkey.com</committed-by>
                <activity>
                    <attribute>
                        <name>Status</name>
                        <value>Closed</value>
                        <type>combo-box</type>
                    </attribute>
                    <description>
                        Status set to Closed
                    </description>
                </activity>
            </activity-set>
            
            <dependency>
                <type>blocking</type>
                <child>TBNS304</child>
            </dependency>
        </issue>
    </module>
</scarab>
