=== ASSERT-KTH/cvs-vintage/contrib/tiles/src/share/org/apache/struts/tiles/resources/tiles-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by  () -->
<!--DTD generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!ELEMENT component-definitions (definition+)>
<!ELEMENT tiles-definitions (definition+)>
<!ELEMENT definition (put*, putList*)>
<!ATTLIST definition
	name CDATA #REQUIRED
	path CDATA #IMPLIED
	extends CDATA #IMPLIED
	role CDATA #IMPLIED
	template CDATA #IMPLIED
>
<!ELEMENT put (#PCDATA)>
<!ATTLIST put
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	type (string | page | template | definition) #IMPLIED
	content CDATA #IMPLIED
	direct (true | false) #IMPLIED
>
<!ELEMENT putList (add+)>
<!ATTLIST putList
	name CDATA #REQUIRED
>
<!ELEMENT add EMPTY>
<!ATTLIST add
	value CDATA #REQUIRED
>

=== ASSERT-KTH/cvs-vintage/contrib/tiles/web/channel/WEB-INF/componentDefinitions_silver.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

 <!DOCTYPE tiles-definitions PUBLIC
       "-//Apache Software Foundation//DTD Tiles Configuration//EN"
       "http://jakarta.apache.org/struts/dtds/tiles-config.dtd">


<!-- html definition Mappings  -->
<tiles-definitions>

  <!-- Main Layout Definition description  -->
  <definition name="mainLayout" >
	  <put name="title"  value="World Financial Online - Silver" />
	  <!-- <put name="header" value="/common/header.jsp" />  -->
	  <put name="footer" value="/silver/common/footer.jsp" />
	  <!-- <put name="menu"   value="menu.main" />  -->
	  <!-- <put name="body"   value="main.portal.body" />  -->
  </definition>
  
  <!-- select language menu -->
<definition name="menu.lang" path="/common/submenu.jsp" >
  <put name="title" value="Langue" />
  <putList name="items" >
    <add value="Gold" />
    <add value="Bronze" />
  </putList>
  <putList name="links" >
    <add value="/priviledge.do?priviledge=gold" />
    <add value="/priviledge.do?priviledge=bronze" />
  </putList>
</definition>

</tiles-definitions>

=== ASSERT-KTH/cvs-vintage/contrib/struts-faces/web/example2/WEB-INF/tiles-defs.xml
<!DOCTYPE tiles-definitions PUBLIC
  "-//Apache Software Foundation//DTD Tiles Configuration//EN"
  "http://jakarta.apache.org/struts/dtds/tiles-config.dtd">

<tiles-definitions>


  <!-- ========== LAYOUTS ========== -->

  <!-- Base Layout -->
  <definition name=".base"         page="/layout.faces">
    <put      name="header"       value="/header.jsp"/>
    <put      name="footer"       value="/footer.jsp"/>
    <put      name="menu"         value="/blank.jsp"/>
    <put      name="body"         value="/blank.jsp"/>
  </definition>

  <!-- Logged Off Layout -->
  <definition name=".loggedoff" extends=".base">
    <put      name="menu"         value="/loggedoff.jsp"/>
  </definition>

  <!-- Logged On Layout -->
  <definition name=".loggedon"  extends=".base">
    <put      name="menu"         value="/loggedon.jsp"/>
  </definition>


  <!-- ========== PAGES ========== -->

  <definition name=".logon"     extends=".loggedoff">
    <put      name="body"         value="/logon.jsp"/>
  </definition>

  <definition name=".mainMenu"  extends=".loggedon">
    <put      name="body"         value="/mainMenu.jsp"/>
  </definition>

  <definition name=".register"  extends=".loggedoff">
    <put      name="body"         value="/registration.jsp"/>
  </definition>

  <definition name=".registration"
                                extends=".loggedon">
    <put      name="body"         value="/registration.jsp"/>
  </definition>

  <definition name=".subscription"
                                extends=".loggedon">
    <put      name="body"         value="/subscription.jsp"/>
  </definition>

  <definition name=".welcome"   extends=".loggedoff">
  </definition>


</tiles-definitions>
